AWSTemplateFormatVersion: '2010-09-09'

Description: This AWS CloudFormation Template that configures the Container DevSecOps workshop. 


Resources:

  AnchoreVpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        EnvironmentName: container-devsecops-wksp
      TemplateURL: https://aws-tw-sa-workshop.s3-ap-northeast-1.amazonaws.com/devsecops/containers/anchore-vpc.yml

  AnchoreStack:
    DependsOn: AnchoreVpcStack
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ResourceName: container-devsecops-wksp
      TemplateURL: https://aws-tw-sa-workshop.s3-ap-northeast-1.amazonaws.com/devsecops/containers/anchore-fargate.yml

  InitialPipeline:
    DependsOn: AnchoreStack
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ResourceName: container-devsecops-wksp
        FailWhen: High
      TemplateURL: https://aws-tw-sa-workshop.s3-ap-northeast-1.amazonaws.com/devsecops/containers/pipeline-setup.yml
  

Outputs: {}